name: Node CI

on: [push]

jobs:
  windows_test:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: integration test
      run: |
        yarn install --network-timeout 1000000
        yarn integration:win -t "shared project"
      env:
        REACT_APP_SPECTRON: true
        APPVEYOR: true
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install, build, and test
      run: |
        yarn install --frozen-lockfile
        yarn format --list-different
        yarn lint
        yarn tsc
        yarn test
        (cd homepage && yarn install --frozen-lockfile && yarn build)
      env:
        CI: true
